## Import Libraries

In [69]:
import numpy as np 
import pandas as pd

## Load the Data

In [70]:
df = pd.read_csv('Top Ranked Real Movies Dataset.csv')
df.info

df = df.drop(columns=['Unnamed: 0'])
display(df.head())

,Movie Name,Year of Release,Watch Time,Movie Rating,Meatscore of movie,Votes,Gross,Description
0,Jai Bhim,-2021,164 min,9.4,NaN,"180,702",NaN,When a tribal man is arrested for a case of al...
1,Soorarai Pottru,-2020,153 min,9.3,NaN,"108,490",NaN,"Nedumaaran Rajangam ""Maara"" sets out to make t..."
2,The Shawshank Redemption,-1994,142 min,9.3,81.0,"2,559,534",$28.34M,Two imprisoned men bond over a number of years...
3,The Godfather,-1972,175 min,9.2,100.0,"1,761,949",$134.97M,The aging patriarch of an organized crime dyna...
4,The Dark Knight,-2008,152 min,9.1,84.0,"2,519,388",$534.86M,When the menace known as the Joker wreaks havo...

## Custome Functions

In [71]:
def movie_grade(s):
    if s >= 8:
        return 'A'
    elif s <8 and s>= 6:
        return 'B'
    elif s <6 and s>= 4:
        return 'C'
    else:
        return 'D'

df['Movie Grade'] = df['Movie Rating'].apply(movie_grade)
df[['Movie Rating','Movie Grade']]

      Movie Rating Movie Grade
0              9.4           A
1              9.3           A
2              9.3           A
3              9.2           A
4              9.1           A
...            ...         ...
997            7.6           B
998            7.6           B
999            7.6           B
1000           8.4           A
1001           8.2           A

[1002 rows x 2 columns]

In [72]:
# to get percentage
df ['Movie Rating'].apply(lambda a : np.divide(a,10)*100 )

0       94.0
1       93.0
2       93.0
3       92.0
4       91.0
        ...
997     76.0
998     76.0
999     76.0
1000    84.0
1001    82.0
Name: Movie Rating, Length: 1002, dtype: float64

In [ ]:
df['Votes'] = df['Votes'].str.replace(',','')
df['Votes'] = pd.to_numeric(df['Votes'],errors='coerce')
df['Votes'].head(3)

0     180702
1     108490
2    2559534
Name: Votes, dtype: int64

In [76]:
df['votes_rating_ratio'] = np.divide(df['Votes'], df['Movie Rating'])
df[['Votes','Movie Rating','votes_rating_ratio']].head()

     Votes  Movie Rating  votes_rating_ratio
0   180702           9.4        19223.617021
1   108490           9.3        11665.591398
2  2559534           9.3       275218.709677
3  1761949           9.2       191516.195652
4  2519388           9.1       276855.824176