## Import Libraries

In [2]:
import numpy as np
import pandas as pd

## Load the Dataset

In [6]:
df = pd.read_csv('marketing_campaign.csv', sep='\t')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 29 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   2240 non-null   int64
 1   Year_Birth           2240 non-null   int64
 2   Education            2240 non-null   str
 3   Marital_Status       2240 non-null   str
 4   Income               2216 non-null   float64
 5   Kidhome              2240 non-null   int64
 6   Teenhome             2240 non-null   int64
 7   Dt_Customer          2240 non-null   str
 8   Recency              2240 non-null   int64
 9   MntWines             2240 non-null   int64
 10  MntFruits            2240 non-null   int64
 11  MntMeatProducts      2240 non-null   int64
 12  MntFishProducts      2240 non-null   int64
 13  MntSweetProducts     2240 non-null   int64
 14  MntGoldProds         2240 non-null   int64
 15  NumDealsPurchases    2240 non-null   int64
 16  NumWebPurchases      2240 non-null   int64
 17  NumCatalogPurchases  2240 non-null   int64
 18  NumStorePurchases    2240 non-null   int64
 19  NumWebVisitsMonth    2240 non-null   int64
 20  AcceptedCmp3         2240 non-null   int64
 21  AcceptedCmp4         2240 non-null   int64
 22  AcceptedCmp5         2240 non-null   int64
 23  AcceptedCmp1         2240 non-null   int64
 24  AcceptedCmp2         2240 non-null   int64
 25  Complain             2240 non-null   int64
 26  Z_CostContact        2240 non-null   int64
 27  Z_Revenue            2240 non-null   int64
 28  Response             2240 non-null   int64
dtypes: float64(1), int64(25), str(3)
memory usage: 507.6 KB

In [10]:
df.sample(10, ignore_index=True)

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0,7053,1966,PhD,Single,78420.0,0,0,29-06-2013,75,604,...,1,0,0,0,0,0,0,3,11,0
1,6374,1954,PhD,Married,36930.0,0,1,17-05-2013,50,223,...,8,0,0,0,0,0,0,3,11,0
2,9850,1972,2n Cycle,Married,24884.0,1,0,29-11-2012,32,3,...,7,0,0,0,0,0,0,3,11,0
3,7264,1978,2n Cycle,Single,52195.0,2,1,12-05-2014,2,12,...,8,0,0,0,0,0,0,3,11,0
4,5866,1974,Graduation,Together,48186.0,1,0,20-03-2014,39,97,...,7,0,0,0,0,0,0,3,11,0
5,4887,1976,PhD,Divorced,55412.0,1,1,22-11-2013,65,10,...,5,0,0,0,0,0,0,3,11,0
6,11121,1981,Graduation,Married,19419.0,1,0,10-11-2012,76,2,...,9,0,0,0,0,0,0,3,11,0
7,5430,1956,Graduation,Together,54450.0,1,1,14-09-2012,0,454,...,8,0,0,0,0,0,0,3,11,0
8,9617,1951,Graduation,Single,15033.0,0,0,16-04-2014,37,0,...,3,0,0,0,0,0,0,3,11,0
9,7300,1952,Graduation,Divorced,69142.0,0,1,29-06-2014,50,448,...,5,0,1,0,0,0,0,3,11,0

In [26]:
mask = df['Year_Birth'] > 1990
df[mask][['Year_Birth','Education']].reset_index(drop=True)

    Year_Birth   Education
0         1996    2n Cycle
1         1991         PhD
2         1991  Graduation
3         1992      Master
4         1992      Master
5         1993  Graduation
6         1991         PhD
7         1994  Graduation
8         1992  Graduation
9         1991  Graduation
10        1995  Graduation
11        1991  Graduation
12        1995  Graduation
13        1992  Graduation
14        1991    2n Cycle
15        1991       Basic
16        1992  Graduation
17        1994  Graduation
18        1993  Graduation
19        1993  Graduation
20        1995  Graduation
21        1991  Graduation
22        1992  Graduation
23        1994  Graduation
24        1996       Basic
25        1991      Master
26        1991         PhD
27        1992       Basic
28        1993  Graduation
29        1992       Basic
30        1991      Master
31        1992  Graduation
32        1991    2n Cycle
33        1992       Basic
34        1991  Graduation
35        1992  Graduation
36        1995    2n Cycle
37        1991  Graduation
38        1991  Graduation
39        1992    2n Cycle
40        1993  Graduation
41        1992       Basic
42        1995    2n Cycle

In [33]:
df[(df['Education'] =='Graduation') & (df['Year_Birth'] > 1990)]['ID'].reset_index(drop=True)

0       999
1      2669
2      5067
3      3386
4      9214
5      8315
6     11101
7     10548
8      8560
9      4654
10    10619
11     4483
12    10037
13     5184
14    10749
15     3005
16     6905
17     5080
18     8175
19      569
20    10513
21     4552
22     5631
23     7734
Name: ID, dtype: int64