## import Libraries

In [13]:
import pandas as pd

#### 🟦 `pd.read_csv`

| پارامتر | توضیح کوتاه | کاربرد اصلی | مثال کوتاه |
|----------|-------------|--------------|-------------|
| `filepath_or_buffer` | مسیر یا URL فایل | بارگذاری داده | `pd.read_csv("data.csv")` |
| `sep` | جداکننده ستون‌ها | فایل‌های با `;` یا `|` | `pd.read_csv("d.csv", sep=";")` |
| `encoding` | نوع کدگذاری متن |/korean رفع مشکل متن فارسی | `pd.read_csv("fa.csv", encoding="utf-8")` |
| `header` | ردیف عنوان ستون‌ها | فایل بدون هدر | `pd.read_csv("d.csv", header=None)` |
| `usecols` | انتخاب ستون‌ها | کاهش حافظه | `pd.read_csv("d.csv", usecols=["id","city"])` |
| `nrows` | تعداد ردیف برای خواندن | پیش‌نمایش سریع | `pd.read_csv("big.csv", nrows=1000)` |
| `chunksize` | اندازه قطعه | پردازش فایل‌های بزرگ | `for c in pd.read_csv("big.csv", chunksize=50000): pass` |

In [17]:
# df = pd.read_csv('C:\Users\as\Desktop\NumPy.basics\Pandas\3_work_with_files\marketing_campaign.csv')
df = pd.read_csv('marketing_campaign.csv', sep='\t')
df
#df1 = pd.read_csv('marketing_campaign.csv', sep='\t', header = None)
df.info()
df.head()

<class 'pandas.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 29 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   2240 non-null   int64
 1   Year_Birth           2240 non-null   int64
 2   Education            2240 non-null   str
 3   Marital_Status       2240 non-null   str
 4   Income               2216 non-null   float64
 5   Kidhome              2240 non-null   int64
 6   Teenhome             2240 non-null   int64
 7   Dt_Customer          2240 non-null   str
 8   Recency              2240 non-null   int64
 9   MntWines             2240 non-null   int64
 10  MntFruits            2240 non-null   int64
 11  MntMeatProducts      2240 non-null   int64
 12  MntFishProducts      2240 non-null   int64
 13  MntSweetProducts     2240 non-null   int64
 14  MntGoldProds         2240 non-null   int64
 15  NumDealsPurchases    2240 non-null   int64
 16  NumWebPurchases      2240 non-null   int64
 17  NumCatalogPurchases  2240 non-null   int64
 18  NumStorePurchases    2240 non-null   int64
 19  NumWebVisitsMonth    2240 non-null   int64
 20  AcceptedCmp3         2240 non-null   int64
 21  AcceptedCmp4         2240 non-null   int64
 22  AcceptedCmp5         2240 non-null   int64
 23  AcceptedCmp1         2240 non-null   int64
 24  AcceptedCmp2         2240 non-null   int64
 25  Complain             2240 non-null   int64
 26  Z_CostContact        2240 non-null   int64
 27  Z_Revenue            2240 non-null   int64
 28  Response             2240 non-null   int64
dtypes: float64(1), int64(25), str(3)
memory usage: 507.6 KB

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0,5524,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,635,...,7,0,0,0,0,0,0,3,11,1
1,2174,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,11,...,5,0,0,0,0,0,0,3,11,0
2,4141,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,426,...,4,0,0,0,0,0,0,3,11,0
3,6182,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,11,...,6,0,0,0,0,0,0,3,11,0
4,5324,1981,PhD,Married,58293.0,1,0,19-01-2014,94,173,...,5,0,0,0,0,0,0,3,11,0

#### 🟥 `DataFrame.to_csv`

| پارامتر | توضیح کوتاه | کاربرد اصلی | مثال کوتاه |
|----------|-------------|--------------|-------------|
| `path_or_buf` | مسیر خروجی | ذخیره CSV | `df.to_csv("out.csv")` |
| `index` | نوشتن ایندکس | حذف ایندکس در خروجی | `df.to_csv("out.csv", index=False)` |
| `encoding` | کدگذاری خروجی | حفظ متن فارسی | `df.to_csv("fa.csv", encoding="utf-8")` |

In [ ]:
df.to_csv('my_csv.csv')         #making a csv file

#### 🟩 `pd.read_excel`

| پارامتر | توضیح کوتاه | کاربرد اصلی | مثال کوتاه |
|----------|-------------|--------------|-------------|
| `io` | مسیر فایل Excel | بارگذاری داده | `pd.read_excel("data.xlsx")` |
| `sheet_name` | نام یا شماره شیت | انتخاب شیت خاص | `pd.read_excel("d.xlsx", sheet_name="Sales")` |
| `usecols` | انتخاب ستون‌ها | خواندن ستون‌های ضروری | `pd.read_excel("d.xlsx", usecols="A:D")` |
| `skiprows` | پرش از ردیف‌ها | حذف توضیحات اضافی | `pd.read_excel("d.xlsx", skiprows=2)` |

In [30]:
df2 = pd.read_excel('my_excel.xlsx',usecols=[0,1,2,3,4])
df2.head()

   Unnamed: 0    ID  Year_Birth   Education Marital_Status
0           0  5524        1957  Graduation         Single
1           1  2174        1954  Graduation         Single
2           2  4141        1965  Graduation       Together
3           3  6182        1984  Graduation       Together
4           4  5324        1981         PhD        Married

#### 🟪 `DataFrame.to_excel`

| پارامتر | توضیح کوتاه | کاربرد اصلی | مثال کوتاه |
|----------|-------------|--------------|-------------|
| `excel_writer` | مسیر خروجی | ذخیره Excel | `df.to_excel("out.xlsx")` |
| `sheet_name` | نام شیت | سازمان‌دهی خروجی | `df.to_excel("out.xlsx", sheet_name="Results")` |
| `index` | نوشتن ایندکس | خروجی تمیز برای اشتراک | `df.to_excel("out.xlsx", index=False)` |

In [27]:
df.to_excel('my_excel.xlsx', sheet_name='sheet_1')

#### 🟨 `pd.read_json`

| پارامتر | توضیح کوتاه | کاربرد اصلی | مثال کوتاه |
|----------|-------------|--------------|-------------|
| `path_or_buf` | مسیر یا رشته JSON | بارگذاری داده | `pd.read_json("data.json")` |
| `orient` | ساختار JSON | سازگاری با API | `pd.read_json("d.json", orient="records")` |
| `lines` | پردازش خط‌به‌خط | فایل‌های لاگ یا NDJSON | `pd.read_json("logs.json", lines=True)` |

In [37]:
df3 = pd.read_json('my_json.json')
df3

      Unnamed: 0     ID  Year_Birth   Education Marital_Status
0              0   5524        1957  Graduation         Single
1              1   2174        1954  Graduation         Single
2              2   4141        1965  Graduation       Together
3              3   6182        1984  Graduation       Together
4              4   5324        1981         PhD        Married
...          ...    ...         ...         ...            ...
2235        2235  10870        1967  Graduation        Married
2236        2236   4001        1946         PhD       Together
2237        2237   7270        1981  Graduation       Divorced
2238        2238   8235        1956      Master       Together
2239        2239   9405        1954         PhD        Married

[2240 rows x 5 columns]

#### 🟫 `DataFrame.to_json`

| پارامتر | توضیح کوتاه | کاربرد اصلی | مثال کوتاه |
|----------|-------------|--------------|-------------|
| `path_or_buf` | مسیر خروجی | ذخیره JSON | `df.to_json("out.json")` |
| `orient` | ساختار خروجی | سازگاری با API | `df.to_json("out.json", orient="records")` |
| `force_ascii` | اجبار به ASCII | برای متن فارسی False | `df.to_json("fa.json", force_ascii=False)` |

In [35]:
df2.to_json('my_json.json')